version: '3'
services:
  middleware-application:
    image: "governikus/eidas-middleware-application:1.0.6"
    ports:
      - "8448:8443"
    volumes:
      - ./mw-config:/opt/eidas-middleware/config
      - mw-database-test:/opt/eidas-middleware/database
volumes:
  mw-database-test:
    external: true
